<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Designation;
use App\Models\Level;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class DesignationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'name' => 'HR',
                'department' => 'Human Resources',
                'level' => 'Junior',
                'reporting_to' => 'Supervisor',
                'description' => 'Handles HR operations and employee coordination',
                'is_active' => true,
            ],
            [
                'name' => 'Operations',
                'department' => 'Operations',
                'level' => 'Senior',
                'reporting_to' => 'Controller',
                'description' => 'Supervises daily transport operations',
                'is_active' => true,
            ],
            // [
            //     'name' => 'Finance Officer',
            //     'department' => 'Finance',
            //     'level' => 'Mid Level',
            //     'reporting_to' => 'Supervisor',
            //     'description' => 'Maintains financial records and approvals',
            //     'is_active' => true,
            // ],
            // [
            //     'name' => 'Admin Coordinator',
            //     'department' => 'Administration',
            //     'level' => 'Mid Level',
            //     'reporting_to' => 'Supervisor',
            //     'description' => 'Coordinates administrative activities',
            //     'is_active' => true,
            // ],
            // [
            //     'name' => 'Maintenance Lead',
            //     'department' => 'Maintenance',
            //     'level' => 'Lead',
            //     'reporting_to' => 'Controller',
            //     'description' => 'Leads fleet maintenance follow-ups',
            //     'is_active' => true,
            // ],
            // [
            //     'name' => 'Support Associate',
            //     'department' => 'Customer Support',
            //     'level' => 'Entry Level',
            //     'reporting_to' => 'Supervisor',
            //     'description' => 'Supports customer query handling',
            //     'is_active' => false,
            // ],
            // [
            //     'name' => 'Fleet Compliance Executive',
            //     'department' => 'Fleet Compliance',
            //     'level' => 'Mid Level',
            //     'reporting_to' => 'Supervisor',
            //     'description' => 'Tracks vehicle and driver compliance documents',
            //     'is_active' => true,
            // ],
            // [
            //     'name' => 'Route Planner',
            //     'department' => 'Route Planning',
            //     'level' => 'Mid Level',
            //     'reporting_to' => 'Controller',
            //     'description' => 'Plans trip routes, stops and schedule coverage',
            //     'is_active' => true,
            // ],
            // [
            //     'name' => 'Vendor Coordinator',
            //     'department' => 'Vendor Management',
            //     'level' => 'Junior',
            //     'reporting_to' => 'Supervisor',
            //     'description' => 'Coordinates OEM and vendor documentation follow-up',
            //     'is_active' => true,
            // ],
        ];

        DB::transaction(function () use ($records) {
            foreach ($records as $record) {
                $department = Department::where('name', $record['department'])->first();
                $level = Level::where('name', $record['level'])->first();
                $reportingRole = Role::where('name', $record['reporting_to'])
                    ->where('name', '!=', 'Super Admin')
                    ->first();

                if (! $department || ! $level || ! $reportingRole) {
                    continue;
                }

                $designationRole = Role::firstOrCreate([
                    'name' => $record['name'],
                    'guard_name' => 'web',
                ]);

                if ($record['name'] === 'HR') {
                    $designationRole->syncPermissions([
                        'branch-locations.create',
                        'branch-locations.edit',
                        'branch-locations.delete',
                        'branch-locations.view',
                        'departments.create',
                        'departments.edit',
                        'departments.delete',
                        'departments.view',
                        'levels.create',
                        'levels.edit',
                        'levels.delete',
                        'levels.view',
                        'designations.create',
                        'designations.edit',
                        'designations.delete',
                        'designations.view',
                        'hrms-document-types.create',
                        'hrms-document-types.edit',
                        'hrms-document-types.delete',
                        'hrms-document-types.view',
                        'leave-types.create',
                        'leave-types.edit',
                        'leave-types.delete',
                        'leave-types.view',
                        'shift-settings.create',
                        'shift-settings.edit',
                        'shift-settings.delete',
                        'shift-settings.view',
                        'holidays.create',
                        'holidays.edit',
                        'holidays.delete',
                        'holidays.view',
                        'salary-components.create',
                        'salary-components.edit',
                        'salary-components.delete',
                        'salary-components.view',
                        'staff-management.create',
                        'staff-management.edit',
                        'staff-management.delete',
                        'staff-management.view',
                        'controller-management.create',
                        'controller-management.edit',
                        'controller-management.delete',
                        'controller-management.view',
                        'supervisor-management.create',
                        'supervisor-management.edit',
                        'supervisor-management.delete',
                        'supervisor-management.view',
                        'driver-management.create',
                        'driver-management.edit',
                        'driver-management.delete',
                        'driver-management.view',
                        'leaves.create',
                        'leaves.edit',
                        'leaves.delete',
                        'leaves.view',
                        'attendance-management.create',
                        'attendance-management.edit',
                        'attendance-management.delete',
                        'attendance-management.view',
                        'trips.create',
                        'trips.edit',
                        'trips.delete',
                        'trips.view',
                        'trips.assign',
                        'trips.sheet',
                        'rosters.create',
                        'rosters.edit',
                        'rosters.delete',
                        'rosters.view',
                        'complaints.create',
                        'complaints.edit',
                        'complaints.delete',
                        'complaints.view',
                        'activity-logs.view',
                        'salary-processing.create',
                        'salary-processing.edit',
                        'salary-processing.delete',
                        'salary-processing.view',
                        'salary-processing.approve',
                        'salary-reports.view',
                        'salary-files.view',
                    ]);
                }

                if ($record['name'] === 'Operations') {
                    $designationRole->syncPermissions([
                        'prefixes.create',
                        'prefixes.edit',
                        'prefixes.delete',
                        'prefixes.view',
                        'states.create',
                        'states.edit',
                        'states.delete',
                        'states.view',
                        'districts.create',
                        'districts.edit',
                        'districts.delete',
                        'districts.view',
                        'locations.create',
                        'locations.edit',
                        'locations.delete',
                        'locations.view',
                        'service-types.create',
                        'service-types.edit',
                        'service-types.delete',
                        'service-types.view',
                        'oem-types.create',
                        'oem-types.edit',
                        'oem-types.delete',
                        'oem-types.view',
                        'depots.create',
                        'depots.edit',
                        'depots.delete',
                        'depots.view',
                        'vehicle-classifications.create',
                        'vehicle-classifications.edit',
                        'vehicle-classifications.delete',
                        'vehicle-classifications.view',
                        'document-types.create',
                        'document-types.edit',
                        'document-types.delete',
                        'document-types.view',
                        'complaint-categories.create',
                        'complaint-categories.edit',
                        'complaint-categories.delete',
                        'complaint-categories.view',
                        'dor-account-responsibles.create',
                        'dor-account-responsibles.edit',
                        'dor-account-responsibles.delete',
                        'dor-account-responsibles.view',
                        'dor-kilometer-loss-reasons.create',
                        'dor-kilometer-loss-reasons.edit',
                        'dor-kilometer-loss-reasons.delete',
                        'dor-kilometer-loss-reasons.view',
                        'oems.create',
                        'oems.edit',
                        'oems.delete',
                        'oems.view',
                        'routes.create',
                        'routes.edit',
                        'routes.delete',
                        'routes.view',
                        'vehicles.create',
                        'vehicles.edit',
                        'vehicles.delete',
                        'vehicles.view',
                        'branch-locations.create',
                        'branch-locations.edit',
                        'branch-locations.delete',
                        'branch-locations.view',
                        'departments.create',
                        'departments.edit',
                        'departments.delete',
                        'departments.view',
                        'levels.create',
                        'levels.edit',
                        'levels.delete',
                        'levels.view',
                        'designations.create',
                        'designations.edit',
                        'designations.delete',
                        'designations.view',
                        'hrms-document-types.create',
                        'hrms-document-types.edit',
                        'hrms-document-types.delete',
                        'hrms-document-types.view',
                        'leave-types.create',
                        'leave-types.edit',
                        'leave-types.delete',
                        'leave-types.view',
                        'shift-settings.create',
                        'shift-settings.edit',
                        'shift-settings.delete',
                        'shift-settings.view',
                        'holidays.create',
                        'holidays.edit',
                        'holidays.delete',
                        'holidays.view',
                        'salary-components.create',
                        'salary-components.edit',
                        'salary-components.delete',
                        'salary-components.view',
                        'staff-management.create',
                        'staff-management.edit',
                        'staff-management.delete',
                        'staff-management.view',
                        'controller-management.create',
                        'controller-management.edit',
                        'controller-management.delete',
                        'controller-management.view',
                        'supervisor-management.create',
                        'supervisor-management.edit',
                        'supervisor-management.delete',
                        'supervisor-management.view',
                        'driver-management.create',
                        'driver-management.edit',
                        'driver-management.delete',
                        'driver-management.view',
                        'leaves.create',
                        'leaves.edit',
                        'leaves.delete',
                        'leaves.view',
                        'attendance-management.create',
                        'attendance-management.edit',
                        'attendance-management.delete',
                        'attendance-management.view',
                        'trips.create',
                        'trips.edit',
                        'trips.delete',
                        'trips.view',
                        'trips.assign',
                        'trips.sheet',
                        'rosters.create',
                        'rosters.edit',
                        'rosters.delete',
                        'rosters.view',
                        'complaints.create',
                        'complaints.edit',
                        'complaints.delete',
                        'complaints.view',
                        'activity-logs.view',
                        'salary-processing.create',
                        'salary-processing.edit',
                        'salary-processing.delete',
                        'salary-processing.view',
                        'salary-processing.approve',
                        'salary-reports.view',
                        'salary-files.view',
                        'dor-reports.view',
                        'license-expiry-reports.view',
                    ]);
                }

                $designation = Designation::firstOrCreate(
                    ['name' => $record['name']],
                    [
                        'department_id' => $department->id,
                        'level_id' => $level->id,
                        'reporting_to' => $reportingRole->id,
                        'role_id' => $designationRole->id,
                        'description' => $record['description'],
                        'is_active' => $record['is_active'],
                    ]
                );

                if (! $designation->role_id) {
                    $designation->role_id = $designationRole->id;
                    $designation->save();
                }

                if (! $designation->code) {
                    $designation->code = generate_code('Designation Module', $designation->id, 3, 'DSG');
                    $designation->save();
                }
            }
        });
    }
}
