@section('title', 'Generated Letters')
<x-app-layout><section class="section dashboard section-top-padding">
<div class="page-title"><h3>Letters - {{ $user->name }}</h3><nav><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li><li class="breadcrumb-item active">HRMS</li><li class="breadcrumb-item active">User Letters</li></ol></nav></div>
<div class="row"><div class="col-lg-12 mb-3"><div class="main-table-container">
    <div class="row"><div class="col-lg-4 ms-auto justify-content-end d-flex btns-group-container">@can('hr-letters.generate')<a href="{{ route('hr-letters.create', $user) }}" class="add-btn form-btn text-decoration-none">Generate Letter</a>@endcan</div></div>
    <div class="row"><div class="col-lg-12"><div class="mt-3 table-container"><table id="table" class="table align-middle mb-0 tble-cstm mt-3" style="width:100%"><thead><tr><th class="text-center">Sl No</th><th class="text-center">Letter No.</th><th class="text-center">Entity</th><th class="text-center">Language</th><th class="text-center">Subject</th><th class="text-center">Generated On</th><th class="text-center">Action</th></tr></thead><tbody></tbody></table></div></div></div>
</div></div></div></section>
@section('scripts')<script>$(function(){$('#table').DataTable({processing:true,serverSide:true,ajax:"{{ route('hr-letters.index', $user) }}",order:[[5,'desc']],columns:[{data:'DT_RowIndex',name:'DT_RowIndex',orderable:false,searchable:false,className:'text-center'},{data:'letter_number',name:'letter_number',className:'text-center'},{data:'entity_label',name:'entity_type',className:'text-center'},{data:'language',name:'language',className:'text-center'},{data:'subject',name:'subject',className:'text-center'},{data:'generated_at',name:'generated_at',className:'text-center'},{data:'action',name:'action',orderable:false,searchable:false,className:'text-center'}]});});</script>@endsection
</x-app-layout>
