@php
    $money = fn ($value) => number_format((float) $value, 2);
    $items = $report['items'];
    $grossTotal = $items->sum(fn ($item) => (float) $item->basic_salary);
    $incentiveTotal = $items->sum(fn ($item) => (float) $item->incentive);
    $deductionTotal = $items->sum(fn ($item) => (float) $item->deduction + (float) $item->lop);
    $netTotal = $items->sum(fn ($item) => (float) $item->net_salary);
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 24px 26px; }
        * { box-sizing: border-box; }
        body { color: #243447; font-family: DejaVu Sans, sans-serif; font-size: 9px; margin: 0; }
        .header { background: #17324d; color: #fff; padding: 18px 20px; }
        .title { font-size: 19px; font-weight: bold; margin: 0 0 5px; }
        .subtitle { color: #d8e7f2; font-size: 10px; }
        .meta { background: #f1f5f9; border-bottom: 1px solid #d7e0e8; padding: 9px 12px; }
        .meta span { margin-right: 28px; }
        .label { color: #6b7c8f; font-size: 8px; text-transform: uppercase; }
        .value { color: #243447; font-weight: bold; }
        .summary { margin: 13px 0 12px; width: 100%; }
        .summary td { background: #f8fafc; border: 1px solid #e1e8ef; padding: 8px 10px; width: 25%; }
        .summary .amount { color: #17324d; font-size: 13px; font-weight: bold; margin-top: 3px; }
        table.data { border-collapse: collapse; width: 100%; }
        .data th { background: #2f6f95; color: #fff; font-size: 8px; padding: 7px 5px; text-align: left; }
        .data td { border-bottom: 1px solid #e3e8ed; padding: 6px 5px; }
        .data tr:nth-child(even) td { background: #f7fafc; }
        .right { text-align: right !important; }
        .center { text-align: center !important; }
        .status { color: #18794e; font-weight: bold; }
        .footer { color: #718096; font-size: 8px; margin-top: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">SYSCON Salary File</div>
        <div class="subtitle">Attendance and wage register</div>
    </div>
    <div class="meta">
        <span><span class="label">Period</span><br><span class="value">{{ $report['monthName'] }} {{ $report['year'] }}</span></span>
        <span><span class="label">Depot</span><br><span class="value">{{ $report['depot']?->name ?? '-' }}</span></span>
        <span><span class="label">Role</span><br><span class="value">{{ $report['roleLabel'] }}</span></span>
        <span><span class="label">Generated</span><br><span class="value">{{ now()->format('d-m-Y h:i A') }}</span></span>
    </div>

    <table class="summary">
        <tr>
            <td><div class="label">Employees</div><div class="amount">{{ $items->count() }}</div></td>
            <td><div class="label">Gross Earnings</div><div class="amount">{{ $money($grossTotal) }}</div></td>
            <td><div class="label">Incentive</div><div class="amount">{{ $money($incentiveTotal) }}</div></td>
            <td><div class="label">Net Salary</div><div class="amount">{{ $money($netTotal) }}</div></td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th class="center">#</th>
                <th>Employee Code</th>
                <th>Employee Name</th>
                <th class="right">Gross Salary</th>
                <th class="right">Incentive</th>
                <th class="right">Deduction</th>
                <th class="right">LOP</th>
                <th class="right">Net Salary</th>
                <th class="center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($items as $index => $item)
                <tr>
                    <td class="center">{{ $index + 1 }}</td>
                    <td>{{ $item->user?->code ?: '-' }}</td>
                    <td>{{ $item->user?->name ?: '-' }}</td>
                    <td class="right">{{ $money($item->basic_salary) }}</td>
                    <td class="right">{{ $money($item->incentive) }}</td>
                    <td class="right">{{ $money($item->deduction) }}</td>
                    <td class="right">{{ $money($item->lop) }}</td>
                    <td class="right"><strong>{{ $money($item->net_salary) }}</strong></td>
                    <td class="center status">{{ $item->salaryProcessing?->status ?: '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="9" class="center">No salary records found in this file.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">Generated by SYSCON &bull; This document is system generated.</div>
</body>
</html>
